### ISSUE TITLE
Unable to start the demo when using newer version of node

### ISSUE THREAD

**Issue by Pkingo** [pactsafe/pactsafe-react-sdk#19]
Hi,
When using a newer version of NodeJS (I was using v12.16.1) the app was unable to start since you are using OutgoingMessage.prototype._headers which was deprecated in v12. https://github.com/http-party/http-server/issues/537
I was able to work around it by using v10.11.0, but it would be nice if I didn't have to change my version in order to make the app run 😄

**Comment by kylepeeler** [comment]
Hey @Pkingo, sorry about that! I'll take a look at getting a newer version bumped shortly so you can use this w/ Node 12!

**Comment by Pkingo** [comment]
Sounds great, and no worries. It wasn't a huge problem, but nice that you are fixing it 👍
