### ISSUE TITLE
PSClickWrap failed to load

### ISSUE THREAD

**Issue by vu-pham** [pactsafe/pactsafe-react-sdk#39]
Hi team,

We are facing the error when using PSClickWrap, it rarely happens. But we can see the error in console log
![image-2021-11-04-15-09-40-328](https://user-images.githubusercontent.com/23306836/142602572-2ee479c9-2b27-4443-aeb1-ab237d07890a.png)
The line is problematic https://github.com/pactsafe/pactsafe-react-sdk/blob/ddda39d0c31688ec541b8d9fda76a5f0a2fdfdad/src/PSSnippet.js#L97

We should check null src before calling indexOf to avoid the issue.

**Comment by Wilsonl9** [comment]
Issue was addressed in the following PR, by adding a null check:

https://github.com/pactsafe/pactsafe-react-sdk/pull/54
